syntax on
colorscheme darkblue
set incsearch                                                                                                                                                                                                                     
set number
set showmatch
set ruler
set cursorline
set expandtab
set tabstop=2
set noautoindent
setlocal formatoptions-=r
setlocal formatoptions-=o
set noswapfile
